### ISSUE TITLE
Mnemonic wallet recovery does not discover cold/hot-balance for cold staking

### ISSUE THREAD

**Issue by viscolex** [SolarisPlatform/SolarisBitcoinFullNode#1]
When recovering a wallet using the mnemonic 12 words, only walletName/account0 gets discovered.

walletName/coldStakingColdAddresses and walletName/coldStakingHotAddresses are not discovered, thus showing no balances and to the user it looks as if they were never set-up before.

The 12 word mnemonic recovery should also discover the Cold and Hot staking addresses if they have been setup for that wallet.

See https://github.com/block-core/blockcore/issues/9 for further details and discussion.

**Comment by keesdewit82** [comment]
The issue got resolved in 36e210a31eac8de5a1e3577eda1f1abdd922e83f
